version: '3.7'

services:
  jenkins:
    image: "jenkins/jenkins:lts-alpine"
    container_name: jenkins
    networks:
    - internal
    restart: unless-stopped  
    volumes:
    - ./jenkins:/var/jenkins_home
    ports:
    - 8080:8080
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: selenoid
    networks:
    - internal
    restart: unless-stopped
    environment:
    - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video/
    ports:
    - 4444:4444
    volumes:
    - "./selenoid:/etc/selenoid/:ro"
    - "./selenoid/video/:/opt/selenoid/video/"
    - "./selenoid/logs/:/opt/selenoid/logs/"
    - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-container-network", "qa_stack_internal"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    container_name: selenoid-ui
    networks:
    - internal
    restart: unless-stopped
    links:
    - selenoid
    ports:
    - 8081:8080
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  internal:
      driver: bridge
