version: '3.7'

services:
  jenkins:
    image: "jenkins/jenkins:lts-alpine"
    container_name: jenkins
    network_mode: bridge
    restart: unless-stopped  
    volumes:
    - ./jenkins:/var/jenkins_home
    ports:
    - 8080:8080
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: selenoid
    network_mode: bridge
    restart: always
    environment:
    - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video/
    ports:
    - "4444:4444"
    volumes:
    - "./selenoid:/etc/selenoid/:ro"
    - "./selenoid/video/:/opt/selenoid/video/"
    - "./selenoid/logs/:/opt/selenoid/logs/"
    - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    container_name: selenoid-ui
    network_mode: bridge
    restart: always
    links:
    - selenoid
    ports:
    - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  internal:
      driver: bridge